# Generated by Django 4.0.4 on 2022-05-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=20)),
                ('typeAdvice', models.CharField(max_length=40)),
                ('idStation', models.CharField(max_length=40)),
                ('value', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertNo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgNo2', models.FloatField()),
                ('type', models.CharField(max_length=40)),
                ('year1', models.IntegerField()),
                ('idStation', models.CharField(max_length=40)),
                ('subtype', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertO3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgO3', models.FloatField()),
                ('idStation', models.CharField(max_length=40)),
                ('subtype', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
                ('type', models.CharField(max_length=40)),
                ('year1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertPm10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgPm10', models.FloatField()),
                ('idStation', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
                ('type', models.CharField(max_length=40)),
                ('year1', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AlertPm2_5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgPm2_5', models.FloatField()),
                ('idStation', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
                ('type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Avg8Hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgCo', models.FloatField()),
                ('avgO3', models.FloatField()),
                ('dateIni', models.IntegerField()),
                ('idStation', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvgDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgCo', models.FloatField()),
                ('avgNo2', models.FloatField()),
                ('avgO3', models.FloatField()),
                ('avgPm1', models.FloatField()),
                ('avgPm10', models.FloatField()),
                ('avgPm2_5', models.FloatField()),
                ('dateIni', models.IntegerField()),
                ('idStation', models.CharField(max_length=40)),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AvgHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avgPm10', models.FloatField()),
                ('avgNo2', models.FloatField()),
                ('avgCo', models.FloatField()),
                ('dateIni', models.FloatField()),
                ('idStation', models.FloatField()),
                ('avgPm2_5', models.FloatField()),
                ('avgO3', models.IntegerField()),
                ('timestamp', models.BigIntegerField()),
            ],
        ),
    ]
