# Generated by Django 4.0.4 on 2022-05-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosSensores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='timestamp',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='advice',
            name='value',
            field=models.CharField(max_length=40),
        ),
    ]
