# Generated by Django 4.0.4 on 2022-05-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosSensores', '0004_alter_advice_timestamp_alter_advice_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
