# Generated by Django 4.0.4 on 2022-05-12 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DatosSensores', '0005_alter_advice_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baterryVolts', models.FloatField()),
                ('batteryCurrent', models.FloatField()),
                ('batteryLevel', models.FloatField()),
                ('co', models.FloatField()),
                ('coC', models.FloatField()),
                ('date', models.BigIntegerField()),
                ('humidity', models.FloatField()),
                ('idStation', models.CharField(max_length=80)),
                ('luminosity', models.FloatField()),
                ('no2', models.FloatField()),
                ('no2C', models.FloatField()),
                ('o3', models.FloatField()),
                ('o3C', models.FloatField()),
                ('pm1', models.FloatField()),
                ('pm10', models.FloatField()),
                ('pm2_5', models.FloatField()),
                ('pressure', models.FloatField()),
                ('serial', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('timestampSensor', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Danger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max', models.FloatField()),
                ('stations', models.CharField(max_length=800)),
                ('times', models.IntegerField()),
                ('min', models.FloatField()),
                ('dangerType', models.CharField(max_length=400)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warningType', models.CharField(max_length=400)),
                ('stations', models.CharField(max_length=800)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='alertno2',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alerto3',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alertpm10',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='alertpm2_5',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='avg8hours',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='avgdiary',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='avghour',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
